Repository Enterprise-CMCS/macpro-mdct-mcr, pull requests merged in 2023-11, with the labels that each got.

#11507 Remove transitive dependency on vm2
  package.json
  services/ui-src/package.json
  services/ui-src/yarn.lock
  yarn.lock
Labels: ready for review

#11508 Main -> Val
  package.json
  services/app-api/handlers/formTemplates/populateTemplatesTable.ts
  services/app-api/handlers/reports/create.ts
  services/app-api/utils/formTemplates/formTemplates.test.ts
  services/app-api/utils/formTemplates/formTemplates.ts
  services/app-api/utils/testing/setupJest.ts
  services/app-api/utils/types/reports.ts
  services/app-api/utils/validation/schemas.ts
  services/ui-src/package.json
  services/ui-src/src/components/export/ExportedReportBanner.tsx
  services/ui-src/src/components/modals/AddEditReportModal.test.tsx
  services/ui-src/src/components/modals/AddEditReportModal.tsx
  services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
  services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.test.tsx
  services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.tsx
  services/ui-src/src/forms/addEditMcparReport/addEditMcparReport.json
  services/ui-src/src/forms/addEditMcparReport/addEditMcparReportWithoutYoY.json
  services/ui-src/src/types/reportContext.ts
  services/ui-src/src/utils/testing/mockReport.tsx
  services/ui-src/yarn.lock
  services/ui/serverless.yml
  tests/cypress/tests/e2e/mcpar/autosave.feature
  tests/cypress/tests/e2e/mcpar/dashboard.feature
  tests/cypress/tests/e2e/mcpar/form.stepdef.js
  tests/cypress/tests/e2e/sidebar.spec.js
  yarn.lock
Labels: ready for review

#11513 Disable MCPAR fields after submission
  services/ui-src/src/components/forms/Form.test.tsx
  services/ui-src/src/components/forms/Form.tsx
Labels: ready for review

#11516 Add a backfill script for previousRevisions, submissionCount
  services/app-api/handlers/etl/addRevisionsToMcpar.test.ts
  services/app-api/handlers/etl/addRevisionsToMcpar.ts
  services/app-api/serverless.yml
Labels: ready for review

#11515 [CMDCT-2] Fix clear prop hiding users answers when they click cancel but come back
  services/ui-src/src/components/reports/ModalDrawerReportPage.tsx
  services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
  services/ui-src/src/utils/forms/forms.test.ts
  services/ui-src/src/utils/forms/forms.ts
  services/ui-src/src/utils/testing/mockForm.tsx
Labels: ready for review

#11519 Fix AV scan
  services/uploads/src/antivirus.js
  services/uploads/src/clamav.js
Labels: ready for review

#11522 [CMDC-3045] Add serverless plugins to reduce files on build/deploy - "EMFILE - too many open files error"
  services/app-api/package.json
  services/app-api/serverless.yml
  services/app-api/yarn.lock
  services/topics/package.json
  services/topics/serverless.yml
  services/topics/yarn.lock
  services/ui-auth/package.json
  services/ui-auth/serverless.yml
  services/ui-auth/yarn.lock
Labels: draft

#11521 Add ETL for adding PCCM as "no" to mcpar metadata on reports created prior to PCCM option
  services/app-api/handlers/etl/addPccmToPastMcpar.test.ts
  services/app-api/handlers/etl/addPccmToPastMcpar.ts
  services/app-api/serverless.yml
Labels: ready for review

#11525 Admin Banner Zustandification™️ (Karla's Version)
  services/ui-src/package.json
  services/ui-src/src/components/banners/AdminBannerProvider.test.tsx
  services/ui-src/src/components/banners/AdminBannerProvider.tsx
  services/ui-src/src/components/pages/Admin/AdminPage.test.tsx
  services/ui-src/src/components/pages/Admin/AdminPage.tsx
  services/ui-src/src/components/pages/Home/HomePage.tsx
  services/ui-src/src/types/banners.ts
  services/ui-src/src/types/index.ts
  services/ui-src/src/types/states.ts
  services/ui-src/src/utils/index.ts
  services/ui-src/src/utils/state/useStore.ts
  services/ui-src/src/utils/testing/mockZustand.tsx
  services/ui-src/src/utils/testing/setupJest.tsx
  services/ui-src/src/verbiage/errors.ts
  services/ui-src/yarn.lock
Labels: in progress

#11526 Dont Dangerously Render HTML
  services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
  services/ui-src/src/components/tables/EntityRow.tsx
  services/ui-src/src/utils/other/rendering.ts
Labels: ready for review
