Repository Enterprise-CMCS/macpro-mdct-mcr, pull requests merged in 2023-05, with the labels that each got.

#11238 API Types Cleanup
  services/app-api/handlers/banners/create.test.ts
  services/app-api/handlers/banners/create.ts
  services/app-api/handlers/banners/delete.test.ts
  services/app-api/handlers/banners/delete.ts
  services/app-api/handlers/banners/fetch.test.ts
  services/app-api/handlers/banners/fetch.ts
  services/app-api/handlers/etl/formTemplateEntitiesUpdate.ts
  services/app-api/handlers/handler-lib.test.ts
  services/app-api/handlers/handler-lib.ts
  services/app-api/handlers/print/printPdf.test.ts
  services/app-api/handlers/print/printPdf.ts
  services/app-api/handlers/reports/archive.test.ts
  services/app-api/handlers/reports/archive.ts
  services/app-api/handlers/reports/create.test.ts
  services/app-api/handlers/reports/create.ts
  services/app-api/handlers/reports/fetch.test.ts
  services/app-api/handlers/reports/fetch.ts
  services/app-api/handlers/reports/release.test.ts
  services/app-api/handlers/reports/release.ts
  services/app-api/handlers/reports/submit.test.ts
  services/app-api/handlers/reports/submit.ts
  services/app-api/handlers/reports/update.test.ts
  services/app-api/handlers/reports/update.ts
  services/app-api/handlers/templates/fetch.test.ts
  services/app-api/handlers/templates/fetch.ts
  services/app-api/utils/auth/authorization.test.ts
  services/app-api/utils/auth/authorization.ts
  services/app-api/utils/dynamo/dynamodb-lib.ts
  services/app-api/utils/s3/s3-lib.test.ts
  services/app-api/utils/s3/s3-lib.ts
  services/app-api/utils/testing/setupJest.ts
  services/app-api/utils/types/banners.ts
  services/app-api/utils/types/formFields.ts
  services/app-api/utils/types/index.ts
  services/app-api/utils/types/other.ts
  services/app-api/utils/types/reportContext.ts
  services/app-api/utils/types/reports.ts
  services/app-api/utils/types/types.ts
  services/app-api/utils/types/users.ts
  services/app-api/utils/validation/completionSchemas.ts
  services/app-api/utils/validation/completionStatus.ts
  services/app-api/utils/validation/completionValidation.ts
  services/app-api/utils/validation/validation.ts
Labels: ready for review

#11243 Swap first-child to first-of-type in footer
  services/ui-src/src/components/layout/Footer.tsx
Labels: ready for review

#11241 Make number validation more strict
  services/app-api/utils/validation/completionSchemas.ts
  services/app-api/utils/validation/schemaMap.ts
  services/ui-src/src/utils/other/mask.test.ts
  services/ui-src/src/utils/other/mask.tsx
  services/ui-src/src/utils/validation/schemas.ts
Labels: ready for review, product review

#11255 MDCT-2407: Improved Test Coverage for Schemas
  services/app-api/utils/validation/schemaMap.test.ts
Labels: ready for review

#11267 [MDCT-2433]: Update answers in access measures modal
  services/app-api/utils/testing/fixtures/completionStatus/mcpar-template.test.json
  services/ui-src/src/forms/mcpar/mcpar.json
Labels: ready for review

#11265 [MDCT-2411] - Drawers + Modals saving too often
  services/ui-src/src/components/modals/AddEditEntityModal.test.tsx
  services/ui-src/src/components/modals/AddEditEntityModal.tsx
  services/ui-src/src/components/reports/DrawerReportPage.test.tsx
  services/ui-src/src/components/reports/DrawerReportPage.tsx
  services/ui-src/src/components/reports/ModalDrawerReportPage.test.tsx
  services/ui-src/src/components/reports/ModalDrawerReportPage.tsx
  services/ui-src/src/utils/reports/entities.ts
Labels: ready for review

#11275 [MDCT-2462] - Update EntityDetails Heading to match design specs
  services/ui-src/src/components/overlays/EntityDetailsOverlay.tsx
Labels: ready for review, design review

#11276 [MDCT-2469] - Some form fields should not accept `N/A`
  services/app-api/utils/validation/completionSchemaMap.ts
  services/app-api/utils/validation/completionSchemas.test.ts
  services/app-api/utils/validation/completionSchemas.ts
  services/app-api/utils/validation/schemaMap.test.ts
  services/app-api/utils/validation/schemaMap.ts
  services/ui-src/src/forms/mlr/mlr.json
  services/ui-src/src/utils/validation/schemaMap.ts
  services/ui-src/src/utils/validation/schemas.test.ts
  services/ui-src/src/utils/validation/schemas.ts
  services/ui-src/src/verbiage/errors.ts
Labels: design review

#11273 [MDCT-2342] - Fix mobile view for Review and Submit page
  services/ui-src/src/components/reports/ReportPageWrapper.tsx
  services/ui-src/src/components/statusing/StatusTable.test.tsx
  services/ui-src/src/components/statusing/StatusTable.tsx
Labels: ready for review

#11277 [MDCT-2440]: Create custom currency mask
  services/ui-src/src/components/fields/NumberField.tsx
  services/ui-src/src/utils/other/mask.tsx
Labels: ready for review

#11274 [MDCT-2448] - MLR PDF Cosmetic and content fixes
  services/ui-src/src/components/export/ExportedEntityDetailsOverlaySection.tsx
  services/ui-src/src/components/export/ExportedEntityDetailsTableRow.tsx
  services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
  services/ui-src/src/components/export/ExportedReportFieldRow.tsx
  services/ui-src/src/components/export/ExportedReportMetadataTable.tsx
  services/ui-src/src/components/overlays/EntityDetailsOverlay.tsx
  services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
  services/ui-src/src/components/tables/EntityRow.test.tsx
  services/ui-src/src/components/tables/EntityRow.tsx
  services/ui-src/src/components/tables/MobileEntityRow.test.tsx
  services/ui-src/src/components/tables/MobileEntityRow.tsx
  services/ui-src/src/utils/reports/reports.test.ts
  services/ui-src/src/utils/testing/mockForm.tsx
Labels: ready for review
