Repository Enterprise-CMCS/macpro-mdct-mcr, pull requests merged in 2023-02, with the labels that each got.

#5794 minor changes related to repo migration
  README.md
  package.json
Labels: ready for review

#5395 autosave tests
  services/ui-src/src/components/fields/ChoiceListField.test.tsx
  services/ui-src/src/components/fields/ChoiceListField.tsx
  services/ui-src/src/components/fields/DateField.test.tsx
  services/ui-src/src/components/fields/DropdownField.test.tsx
  services/ui-src/src/components/fields/DynamicField.test.tsx
  services/ui-src/src/components/fields/NumberField.test.tsx
  services/ui-src/src/components/fields/RadioField.test.tsx
  services/ui-src/src/components/fields/TextField.test.tsx
  services/ui-src/src/utils/autosave/autosave.test.ts
  services/ui-src/src/utils/autosave/autosave.ts
Labels: ready for review

#11080 Autosave txtfix
  services/ui-src/src/components/fields/TextField.tsx
Labels: bug, ready for review

#11094 Nested Choicelist Fix and saving on continue
  services/ui-src/src/components/fields/ChoiceListField.test.tsx
  services/ui-src/src/components/fields/ChoiceListField.tsx
  services/ui-src/src/components/fields/DateField.test.tsx
  services/ui-src/src/components/fields/DateField.tsx
  services/ui-src/src/components/fields/NumberField.test.tsx
  services/ui-src/src/components/fields/NumberField.tsx
  services/ui-src/src/components/fields/RadioField.test.tsx
  services/ui-src/src/components/fields/TextField.test.tsx
  services/ui-src/src/components/fields/TextField.tsx
  services/ui-src/src/components/forms/Form.tsx
  services/ui-src/src/components/reports/ReportPageFooter.tsx
  services/ui-src/src/components/reports/StandardReportPage.test.tsx
  services/ui-src/src/components/reports/StandardReportPage.tsx
Labels: help wanted, ready for review

#11075 MDCT-2241 + MDCT-2214: MLR Kickoff
  services/app-api/handlers/reports/archive.test.ts
  services/app-api/handlers/reports/archive.ts
  services/app-api/handlers/reports/create.test.ts
  services/app-api/handlers/reports/create.ts
  services/app-api/handlers/reports/fetch.test.ts
  services/app-api/handlers/reports/fetch.ts
  services/app-api/handlers/reports/update.test.ts
  services/app-api/handlers/reports/update.ts
  services/app-api/serverless.yml
  services/app-api/utils/constants/constants.ts
  services/app-api/utils/dynamo/hasReportPathParams.ts
  services/app-api/utils/testing/setupJest.ts
  services/ui-src/src/components/fields/ChoiceListField.test.tsx
  services/ui-src/src/components/fields/ChoiceListField.tsx
  services/ui-src/src/components/fields/DateField.test.tsx
  services/ui-src/src/components/fields/DateField.tsx
  services/ui-src/src/components/fields/DropdownField.test.tsx
  services/ui-src/src/components/fields/DropdownField.tsx
  services/ui-src/src/components/fields/DynamicField.test.tsx
  services/ui-src/src/components/fields/DynamicField.tsx
  services/ui-src/src/components/fields/NumberField.test.tsx
  services/ui-src/src/components/fields/NumberField.tsx
  services/ui-src/src/components/fields/TextField.test.tsx
  services/ui-src/src/components/fields/TextField.tsx
  services/ui-src/src/components/modals/AddEditEntityModal.tsx
  services/ui-src/src/components/modals/AddEditProgramModal.tsx
  services/ui-src/src/components/modals/DeleteEntityModal.tsx
  services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
  services/ui-src/src/components/pages/ReviewSubmit/McparReviewSubmitPage.tsx
  services/ui-src/src/components/reports/DrawerReportPage.tsx
  services/ui-src/src/components/reports/ModalDrawerReportPage.tsx
  services/ui-src/src/components/reports/ReportProvider.test.tsx
  services/ui-src/src/components/reports/ReportProvider.tsx
  services/ui-src/src/components/reports/StandardReportPage.tsx
  services/ui-src/src/forms/mlr/index.ts
  services/ui-src/src/forms/mlr/mlr.json
  services/ui-src/src/types/index.ts
  services/ui-src/src/utils/api/requestMethods/report.test.ts
  services/ui-src/src/utils/api/requestMethods/report.ts
  services/ui-src/src/utils/autosave/autosave.test.ts
  services/ui-src/src/utils/autosave/autosave.ts
  services/ui-src/src/utils/reports/routing.ts
  services/ui-src/src/utils/testing/setupJest.tsx
Labels: ready for review, waiting
