Repository Enterprise-CMCS/macpro-mdct-mcr, pull requests merged in 2023-03, with the labels that each got.

#11088 MDCT-2211: AdminDashSelector Form Revision (Adding MLR)
  services/ui-src/src/components/forms/AdminDashSelector.test.tsx
  services/ui-src/src/components/forms/AdminDashSelector.tsx
  services/ui-src/src/forms/adminDashSelector/adminDashSelector.ts
Labels: ready for review

#11089 statusing FE
  services/ui-src/src/components/index.ts
  services/ui-src/src/components/layout/Footer.tsx
  services/ui-src/src/components/pages/ReviewSubmit/McparReviewSubmitPage.tsx
  services/ui-src/src/components/statusing/StatusTable.tsx
  services/ui-src/src/components/statusing/TableRow.tsx
  services/ui-src/src/types/index.ts
  services/ui-src/src/utils/index.ts
  services/ui-src/src/utils/statusing/getRouteStatus.ts
  services/ui-src/src/verbiage/pages/mcpar/mcpar-review-and-submit.ts
  tests/cypress/tests/e2e/mcpar/form.feature
  tests/cypress/tests/e2e/mcpar/form.stepdef.js
Labels: ready for review

#11131 Autosave patch - Dynamic Fields and Autocomplete
  services/ui-src/src/components/fields/DynamicField.tsx
  services/ui-src/src/components/forms/Form.tsx
  services/ui-src/src/utils/forms/forms.ts
Labels: ready for review

#11143 change help desk email address on account page
  services/ui-src/src/verbiage/pages/profile.ts
Labels: ready for review

#11142 MLR Page 2 (Empty State w/ Accordion)
  services/ui-src/src/components/accordions/FormIntroAccordion.tsx
  services/ui-src/src/components/index.ts
  services/ui-src/src/components/modals/AddEditReportModal.test.tsx
  services/ui-src/src/components/reports/ModalDrawerReportPage.tsx
  services/ui-src/src/components/reports/ModalOverlayReportPage.test.tsx
  services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
  services/ui-src/src/components/reports/ReportPageIntro.tsx
  services/ui-src/src/components/reports/ReportPageWrapper.test.tsx
  services/ui-src/src/components/reports/ReportPageWrapper.tsx
  services/ui-src/src/forms/mlr/mlr.json
  services/ui-src/src/types/other.ts
  services/ui-src/src/types/reports.ts
  services/ui-src/src/utils/reports/reports.test.ts
  services/ui-src/src/utils/testing/setupJest.tsx
  services/ui-src/src/verbiage/pages/mlr/mlr-accordions.ts
  tests/cypress/tests/e2e/mcpar/form.stepdef.js
  tests/cypress/tests/e2e/mlr/form.stepdef.js
Labels: ready for review

#11136 okta OIDC serverless changes
  services/ui-auth/README.md
  services/ui-auth/serverless.yml
Labels: ready for review

#11166 add spinner to export report page and enter button on report dashboard
  services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
  services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
  services/ui-src/src/components/pages/Dashboard/MobileDashboardTable.tsx
  services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
Labels: ready for review

#11176 MLR Submission Modal (Hydrate on Edit)
  services/ui-src/src/components/modals/AddEditReportModal.tsx
Labels: ready for review

#11170 MDCT-2235: MLR Page 2 Filled State
  services/ui-src/src/components/index.ts
  services/ui-src/src/components/reports/ModalOverlayReportPage.test.tsx
  services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
  services/ui-src/src/components/reports/ReportPageIntro.tsx
  services/ui-src/src/components/tables/EntityRow.tsx
  services/ui-src/src/components/tables/MobileEntityRow.tsx
  services/ui-src/src/components/tables/Table.tsx
  services/ui-src/src/forms/mlr/mlr.json
  services/ui-src/src/types/reports.ts
  services/ui-src/src/utils/testing/setupJest.tsx
  services/ui-src/src/verbiage/pages/accordion.ts
  services/ui-src/src/verbiage/pages/mlr/mlr-accordions.ts
  tests/cypress/tests/e2e/mlr/release.feature
Labels: ready to merge

#11178 [MDCT-2224, 2239] - Report Overlay Component and MLR Details Form
  services/ui-src/src/components/fields/ChoiceListField.test.tsx
  services/ui-src/src/components/fields/ChoiceListField.tsx
  services/ui-src/src/components/fields/DateField.tsx
  services/ui-src/src/components/fields/DropdownField.tsx
  services/ui-src/src/components/fields/DynamicField.tsx
  services/ui-src/src/components/fields/NumberField.tsx
  services/ui-src/src/components/fields/TextField.tsx
  services/ui-src/src/components/forms/Form.test.tsx
  services/ui-src/src/components/forms/FormLayoutElements.test.tsx
  services/ui-src/src/components/forms/FormLayoutElements.tsx
  services/ui-src/src/components/index.ts
  services/ui-src/src/components/menus/Sidebar.test.tsx
  services/ui-src/src/components/menus/Sidebar.tsx
  services/ui-src/src/components/overlays/EntityDetailsOverlay.test.tsx
  services/ui-src/src/components/overlays/EntityDetailsOverlay.tsx
  services/ui-src/src/components/reports/EntityProvider.test.tsx
  services/ui-src/src/components/reports/EntityProvider.tsx
  services/ui-src/src/components/reports/ModalOverlayReportPage.test.tsx
  services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
  services/ui-src/src/components/reports/ReportPageWrapper.tsx
  services/ui-src/src/components/tables/EntityRow.tsx
  services/ui-src/src/components/tables/MobileEntityRow.tsx
  services/ui-src/src/forms/mlr/mlr.json
  services/ui-src/src/types/formFields.ts
  services/ui-src/src/types/reports.ts
  services/ui-src/src/utils/autosave/autosave.test.ts
  services/ui-src/src/utils/autosave/autosave.ts
  services/ui-src/src/utils/forms/forms.test.ts
  services/ui-src/src/utils/forms/forms.ts
  services/ui-src/src/utils/testing/setupJest.tsx
  services/ui-src/src/verbiage/pages/accordion.ts
  services/ui-src/src/verbiage/pages/overlays.ts
Labels: ready for review, design review

#11177 Update CODEOWNERS
  .github/CODEOWNERS
Labels: ready for review
