Repository Enterprise-CMCS/macpro-mdct-mcr, pull requests merged in 2023-06, with the labels that each got.

#11290 MDCT-2580: Clear data user no longer needs from Drawers/Modals
  services/ui-src/src/components/cards/EntityCard/EntityCardBottomSection.tsx
  services/ui-src/src/components/modals/AddEditEntityModal.tsx
  services/ui-src/src/components/reports/DrawerReportPage.tsx
  services/ui-src/src/components/reports/ModalDrawerReportPage.tsx
  services/ui-src/src/utils/forms/forms.test.ts
  services/ui-src/src/utils/forms/forms.ts
  services/ui-src/src/utils/reports/entities.ts
Labels: ready for review

#11303 [MDCT-2565]: Reorder Report Program Type choices
  services/app-api/utils/testing/fixtures/completionStatus/mlr-template.test.json
  services/ui-src/src/forms/mlr/mlr.json
Labels: ready for review

#11312 Review PDF Button Change
  services/ui-src/src/assets/icons/icon_search_blue.png
  services/ui-src/src/assets/icons/icon_search_white.png
  services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.tsx
Labels: product review

#11291 MDCT-2496: MLR PDF a11y Improvements
  services/ui-src/src/components/export/ExportedEntityDetailsOverlaySection.tsx
  services/ui-src/src/components/export/ExportedEntityDetailsTableRow.tsx
  services/ui-src/src/components/export/ExportedModalOverlayReportSection.test.tsx
  services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
  services/ui-src/src/components/tables/EntityStatusIcon.tsx
Labels: ready to merge

#11318 Update numberfield to send maskedvalue on blur
  services/ui-src/src/components/fields/NumberField.test.tsx
  services/ui-src/src/components/fields/NumberField.tsx
  services/ui-src/src/forms/mlr/mlr.json
  services/ui-src/src/utils/other/mask.test.ts
Labels: ready for review
