Repository Enterprise-CMCS/macpro-mdct-mcr, pull requests merged in 2023-04, with the labels that each got.

#11190 MLR Design Feedback
  services/ui-src/src/components/fields/ChoiceListField.tsx
  services/ui-src/src/components/fields/DateField.tsx
  services/ui-src/src/components/fields/DropdownField.tsx
  services/ui-src/src/components/fields/DynamicField.tsx
  services/ui-src/src/components/fields/NumberField.tsx
  services/ui-src/src/components/fields/TextField.tsx
  services/ui-src/src/components/layout/Header.tsx
  services/ui-src/src/components/reports/EntityProvider.tsx
  services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
  services/ui-src/src/forms/mlr/mlr.json
  services/ui-src/src/types/other.ts
  services/ui-src/src/utils/autosave/autosave.test.ts
  services/ui-src/src/utils/autosave/autosave.ts
  services/ui-src/src/utils/other/parsing.test.tsx
  services/ui-src/src/utils/other/parsing.ts
  services/ui-src/src/utils/validation/schemas.ts
  services/ui-src/src/verbiage/pages/accordion.ts
Labels: ready for review, design review, product review

#11194 MDCT-2387: Add Section Title to Edit Button for Screen Readers
  services/ui-src/src/components/statusing/StatusTable.test.tsx
  services/ui-src/src/components/statusing/StatusTable.tsx
Labels: ready for review

#11192 Small css updates
  services/ui-src/src/components/forms/Form.tsx
  services/ui-src/src/utils/other/export.tsx
Labels: ready to merge

#11201 Add Return Home Link to Get Started Page
  services/ui-src/src/components/pages/GetStarted/ReportGetStartedPage.tsx
Labels: ready for review

#11204 MLR export page 1
  services/ui-src/src/components/export/ExportedReportFieldRow.test.tsx
  services/ui-src/src/components/export/ExportedReportFieldRow.tsx
  services/ui-src/src/components/export/ExportedReportFieldTable.test.tsx
  services/ui-src/src/components/export/ExportedReportFieldTable.tsx
  services/ui-src/src/forms/mlr/mlr.json
Labels: ready for review, design review, product review

#11209 MDCT 2297 Clear Cypress Session on Logout
  tests/cypress/support/step_definitions/authentication.js
  tests/cypress/support/step_definitions/navigation.js
  tests/cypress/tests/e2e/header.feature
  tests/cypress/tests/e2e/header.spec.js
Labels: ready for review

#11195 Update error validation to be more consistent for all fields (except dynamic)
  services/ui-src/src/components/fields/CheckboxField.test.tsx
  services/ui-src/src/components/fields/ChoiceListField.test.tsx
  services/ui-src/src/components/fields/ChoiceListField.tsx
  services/ui-src/src/components/fields/DateField.test.tsx
  services/ui-src/src/components/fields/DateField.tsx
  services/ui-src/src/components/fields/DropdownField.test.tsx
  services/ui-src/src/components/fields/DropdownField.tsx
  services/ui-src/src/components/fields/NumberField.test.tsx
  services/ui-src/src/components/fields/NumberField.tsx
  services/ui-src/src/components/fields/RadioField.test.tsx
  services/ui-src/src/components/fields/TextAreaField.test.tsx
  services/ui-src/src/components/fields/TextAreaField.tsx
  services/ui-src/src/components/fields/TextField.test.tsx
  services/ui-src/src/components/fields/TextField.tsx
  services/ui-src/src/utils/autosave/autosave.ts
Labels: ready for review

#11211 MDCT-2343: MLR Dashboard Accordions (State and Admin Users)
  services/ui-src/src/components/accordions/InstructionsAccordion.tsx
  services/ui-src/src/components/index.ts
  services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
  services/ui-src/src/components/reports/ReportPageIntro.tsx
  services/ui-src/src/verbiage/pages/accordion.ts
  services/ui-src/src/verbiage/pages/mlr/mlr-dashboard.ts
Labels: ready for review

#11226 Update isReportFormPage functions to accurately assess if on a form page
  services/ui-src/src/components/pages/Dashboard/DashboardPage.test.tsx
  services/ui-src/src/forms/mcpar/index.ts
  services/ui-src/src/forms/mlr/index.ts
Labels: ready for review

#11206 MLR Redline Updates
  services/ui-src/src/components/accordions/InstructionsAccordion.tsx
  services/ui-src/src/components/export/ExportedModalOverlayReportSection.test.tsx
  services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
  services/ui-src/src/components/export/ExportedReportWrapper.tsx
  services/ui-src/src/components/fields/RadioField.tsx
  services/ui-src/src/components/forms/FormLayoutElements.tsx
  services/ui-src/src/components/overlays/EntityDetailsOverlay.test.tsx
  services/ui-src/src/components/overlays/EntityDetailsOverlay.tsx
  services/ui-src/src/components/pages/GetStarted/ReportGetStartedPage.tsx
  services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.test.tsx
  services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.tsx
  services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
  services/ui-src/src/components/reports/ReportPageFooter.tsx
  services/ui-src/src/components/reports/ReportPageIntro.tsx
  services/ui-src/src/components/reports/StandardReportPage.tsx
  services/ui-src/src/components/tables/EntityRow.tsx
  services/ui-src/src/components/widgets/SpreadsheetWidget.tsx
  services/ui-src/src/forms/addEditMlrReport/addEditMlrReport.json
  services/ui-src/src/forms/mlr/mlr.json
  services/ui-src/src/verbiage/pages/accordion.ts
  services/ui-src/src/verbiage/pages/home.ts
  services/ui-src/src/verbiage/pages/mlr/mlr-dashboard.ts
  services/ui-src/src/verbiage/pages/mlr/mlr-review-and-submit.ts
  services/ui-src/src/verbiage/pages/overlays.ts
  tests/cypress/tests/e2e/mlr/release.stepdef.js
Labels: ready for review, design review, product review

#11203 MDCT-2313: MLR Statusing
  services/app-api/handlers/reports/submit.ts
  services/app-api/utils/testing/fixtures/completionStatus/mlr-complete-no-remittance.result.test.json
  services/app-api/utils/testing/fixtures/completionStatus/mlr-complete-no-remittance.testdata.test.json
  services/app-api/utils/testing/fixtures/completionStatus/mlr-complete-with-remittance.result.test.json
  services/app-api/utils/testing/fixtures/completionStatus/mlr-complete-with-remittance.testdata.test.json
  services/app-api/utils/testing/fixtures/completionStatus/mlr-missing-reports.result.test.json
  services/app-api/utils/testing/fixtures/completionStatus/mlr-missing-reports.testdata.test.json
  services/app-api/utils/testing/fixtures/completionStatus/mlr-template.test.json
  services/app-api/utils/types/types.ts
  services/app-api/utils/validation/completionSchemas.ts
  services/app-api/utils/validation/completionStatus.test.ts
  services/app-api/utils/validation/completionStatus.ts
  services/ui-src/src/components/export/ExportedEntityDetailsOverlaySection.tsx
  services/ui-src/src/components/export/ExportedEntityDetailsTable.tsx
  services/ui-src/src/components/export/ExportedEntityDetailsTableRow.tsx
  services/ui-src/src/components/export/ExportedModalOverlayReportSection.test.tsx
  services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
  services/ui-src/src/components/export/ExportedSectionHeading.tsx
  services/ui-src/src/components/fields/ChoiceListField.test.tsx
  services/ui-src/src/components/fields/ChoiceListField.tsx
  services/ui-src/src/components/fields/NumberField.tsx
  services/ui-src/src/components/index.ts
  services/ui-src/src/components/overlays/EntityDetailsOverlay.test.tsx
  services/ui-src/src/components/overlays/EntityDetailsOverlay.tsx
  services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
  services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.tsx
  services/ui-src/src/components/reports/EntityProvider.tsx
  services/ui-src/src/components/statusing/StatusTable.test.tsx
  services/ui-src/src/components/statusing/StatusTable.tsx
  services/ui-src/src/components/tables/EntityRow.tsx
  services/ui-src/src/components/tables/EntityStatusIcon.test.tsx
  services/ui-src/src/components/tables/EntityStatusIcon.tsx
  services/ui-src/src/components/tables/MobileEntityRow.tsx
  services/ui-src/src/forms/mlr/mlr.json
  services/ui-src/src/types/reportContext.ts
  services/ui-src/src/types/reports.ts
  services/ui-src/src/utils/index.ts
  services/ui-src/src/utils/other/rendering.ts
  services/ui-src/src/utils/reports/reports.ts
  services/ui-src/src/utils/reports/routing.ts
  services/ui-src/src/utils/testing/setupJest.tsx
  services/ui-src/src/utils/validation/schemas.ts
  services/ui-src/src/utils/validation/validation.ts
  services/ui-src/src/verbiage/pages/accordion.ts
  tests/cypress/tests/e2e/mlr/form.stepdef.js
Labels: draft, in progress

#11235 MDCT-2420: Disable All Fields + Buttons if MLR Report is Locked
  services/ui-src/src/components/fields/ChoiceListField.tsx
  services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
  services/ui-src/src/components/tables/EntityRow.tsx
  services/ui-src/src/components/tables/MobileEntityRow.tsx
Labels: draft
