Repository Enterprise-CMCS/macpro-mdct-mcr, pull requests merged in 2023-07, with the labels that each got.

#11330 MLR Integration Test Fragility
  services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.tsx
  tests/cypress/tests/e2e/mlr/form.stepdef.js
  tests/cypress/tests/e2e/mlr/release.stepdef.js
Labels: ready for review

#11355 [MDCT-2684] Number Validation Fixes
  services/ui-src/src/components/fields/NumberField.tsx
  services/ui-src/src/utils/validation/schemas.ts
Labels: ready for review

#11368 [MDCT-2685] Make Numberfields show they are nested under Choicelists
  .github/workflows/deploy.yml
  services/ui-src/src/components/fields/NumberField.tsx
Labels: ready for review, product review

#11335 Refactor masking
  services/ui-src/src/components/fields/NumberField.test.tsx
  services/ui-src/src/components/fields/NumberField.tsx
  services/ui-src/src/utils/other/checkInputValidity.test.tsx
  services/ui-src/src/utils/other/checkInputValidity.ts
  services/ui-src/src/utils/other/clean.test.tsx
  services/ui-src/src/utils/other/clean.ts
  services/ui-src/src/utils/other/mask.test.ts
  services/ui-src/src/utils/other/mask.tsx
  services/ui-src/src/utils/validation/schemas.test.ts
  services/ui-src/src/utils/validation/schemas.ts
Labels: ready for review, in progress

#11376 Handle undefined cases in repeated fields for completionstatus
  services/app-api/utils/validation/completionStatus.ts
Labels: ready for review, product review

#11374 [MDCT-2712]: Update fields so they no longer trigger validations between same page types
  services/ui-src/src/components/drawers/ReportDrawer.test.tsx
  services/ui-src/src/components/drawers/ReportDrawer.tsx
  services/ui-src/src/components/fields/ChoiceListField.test.tsx
  services/ui-src/src/components/fields/ChoiceListField.tsx
  services/ui-src/src/components/fields/DateField.test.tsx
  services/ui-src/src/components/fields/DateField.tsx
  services/ui-src/src/components/fields/DropdownField.test.tsx
  services/ui-src/src/components/fields/DropdownField.tsx
  services/ui-src/src/components/fields/NumberField.test.tsx
  services/ui-src/src/components/fields/NumberField.tsx
  services/ui-src/src/components/fields/TextField.test.tsx
  services/ui-src/src/components/fields/TextField.tsx
  services/ui-src/src/components/forms/AdminBannerForm.test.tsx
  services/ui-src/src/components/forms/AdminBannerForm.tsx
  services/ui-src/src/components/forms/AdminDashSelector.tsx
  services/ui-src/src/components/forms/Form.test.tsx
  services/ui-src/src/components/forms/Form.tsx
  services/ui-src/src/components/modals/AddEditEntityModal.test.tsx
  services/ui-src/src/components/modals/AddEditEntityModal.tsx
  services/ui-src/src/components/modals/AddEditReportModal.test.tsx
  services/ui-src/src/components/modals/AddEditReportModal.tsx
  services/ui-src/src/components/overlays/EntityDetailsOverlay.tsx
  services/ui-src/src/components/reports/StandardReportPage.tsx
Labels: ready for review

#11386 REDIRECT_SIGNOUT - Updated
  .env_example
  services/ui-src/.env_example
  services/ui-src/serverless.yml
  services/ui-src/src/config.ts
  services/ui-src/src/utils/auth/UserProvider.tsx
Labels: ready for review
