Repository Enterprise-CMCS/macpro-mdct-mcr, pull requests merged in 2025-05, with the labels that each got.

#12137 NAAAR PDF: Show 438.206 non-compliance details
  services/ui-src/src/components/export/ExportedEntityDetailsTable.test.tsx
  services/ui-src/src/components/export/ExportedEntityDetailsTable.tsx
  services/ui-src/src/components/export/ExportedEntityDetailsTableRow.tsx
  services/ui-src/src/components/export/ExportedPlanOverlayReportSection.tsx
  services/ui-src/src/utils/other/export.test.tsx
  services/ui-src/src/utils/other/export.tsx
  services/ui-src/src/utils/testing/mockForm.tsx
  services/ui-src/src/verbiage/pages/mcpar/mcpar-export.ts
  services/ui-src/src/verbiage/pages/mlr/mlr-export.ts
  services/ui-src/src/verbiage/pages/naaar/naaar-export.ts
Labels: ready for review

#12145 NAAAR PDF: Add standards display info to non-compliance cards
  services/ui-src/src/components/cards/EntityCard/EntityCardBottomSection.tsx
  services/ui-src/src/components/cards/EntityCard/EntityCardTopSection.tsx
Labels: ready for review

#12144 NAAAR PDF: Add cards for 438.68 non compliant standards with basic details
  services/ui-src/src/components/cards/Card.tsx
  services/ui-src/src/components/cards/EntityCard/EntityCardBottomSection.tsx
  services/ui-src/src/components/cards/EntityCard/EntityCardTopSection.tsx
  services/ui-src/src/components/export/ExportedPlanComplianceCard.tsx
  services/ui-src/src/components/export/ExportedPlanOverlayReportSection.tsx
  services/ui-src/src/components/index.ts
  services/ui-src/src/utils/reports/entities.ts
Labels: ready for review

#12141 Refactor verbiage
  logs/launchdarkly-flags.log
  services/ui-src/src/components/cards/Card.tsx
  services/ui-src/src/components/cards/EntityCard/EntityCardBottomSection.tsx
  services/ui-src/src/components/cards/EntityCard/EntityCardTopSection.tsx
  services/ui-src/src/components/export/ExportedEntityDetailsOverlaySection.tsx
  services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
  services/ui-src/src/components/export/ExportedPlanComplianceCard.tsx
  services/ui-src/src/components/export/ExportedPlanOverlayReportSection.tsx
  services/ui-src/src/components/export/ExportedReportBanner.tsx
  services/ui-src/src/components/export/ExportedSectionHeading.tsx
  services/ui-src/src/components/index.ts
  services/ui-src/src/components/layout/InfoSection.tsx
  services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
  services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
  services/ui-src/src/components/pages/GetStarted/ReportGetStartedPage.tsx
  services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.tsx
  services/ui-src/src/utils/index.ts
  services/ui-src/src/utils/other/export.test.tsx
  services/ui-src/src/utils/other/export.tsx
  services/ui-src/src/utils/reports/entities.ts
  services/ui-src/src/utils/verbiage/verbiage.test.ts
  services/ui-src/src/utils/verbiage/verbiage.ts
Labels: ready for review

#12150 NAAAR PDF non-compliance card feature: tests and cleanup
  services/ui-src/src/components/cards/Card.tsx
  services/ui-src/src/components/export/ExportedPlanComplianceCard.test.tsx
  services/ui-src/src/components/export/ExportedPlanComplianceCard.tsx
  services/ui-src/src/components/export/ExportedPlanOverlayReportSection.tsx
  services/ui-src/src/utils/other/export.test.tsx
Labels: ready for review

#12156 NAAAR PDF non-compliance card feature: more tests and cleanup
  services/ui-src/src/components/export/ExportedEntityDetailsTable.tsx
  services/ui-src/src/components/export/ExportedPlanComplianceCard.test.tsx
  services/ui-src/src/components/export/ExportedPlanComplianceCard.tsx
  services/ui-src/src/components/export/ExportedPlanOverlayReportSection.test.tsx
  services/ui-src/src/components/export/ExportedPlanOverlayReportSection.tsx
  services/ui-src/src/utils/reports/entities.test.ts
Labels: ready for review

#12153 Fix 438.68 compliance statusing and field data
  services/ui-src/src/components/overlays/EntityDetailsMultiformOverlay.test.tsx
  services/ui-src/src/components/overlays/EntityDetailsMultiformOverlay.tsx
Labels: ready for review

#12155 [CMDCT-4623] MCPAR Program Name Update - July 2025 Change
  logs/launchdarkly-flags.log
  services/app-api/utils/testing/setupJest.ts
  services/app-api/utils/types/reportContext.ts
  services/app-api/utils/types/reports.ts
  services/app-api/utils/validation/completionSchemaMap.ts
  services/app-api/utils/validation/completionSchemas.test.ts
  services/app-api/utils/validation/completionSchemas.ts
  services/app-api/utils/validation/schemaMap.ts
  services/app-api/utils/validation/schemas.ts
  services/ui-src/src/components/fields/DropdownField.tsx
  services/ui-src/src/components/modals/AddEditReportModal.test.tsx
  services/ui-src/src/components/modals/AddEditReportModal.tsx
  services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
  services/ui-src/src/forms/addEditMcparReport/addEditMcparReport.json
  services/ui-src/src/forms/addEditMcparReport/mcparProgramList.ts
  services/ui-src/src/types/reportContext.ts
  services/ui-src/src/types/reports.ts
  services/ui-src/src/utils/forms/forms.test.ts
  services/ui-src/src/utils/forms/forms.ts
  services/ui-src/src/utils/testing/mockReport.tsx
  tests/cypress/e2e/mcpar/dashboard.cy.js
  tests/cypress/e2e/mcpar/form.cy.js
  tests/cypress/e2e/sidebar.cy.js
Labels: ready for review

#12159 A11y: `autocomplete` field attribute fix
  services/ui-src/src/components/forms/Form.test.tsx
  services/ui-src/src/utils/forms/forms.ts
Labels: ready for review

#12146 NAAAR PDF: Non-compliance details
  logs/launchdarkly-flags.log
  services/ui-src/src/components/cards/Card.tsx
  services/ui-src/src/components/cards/EntityCard/EntityCardBottomSection.tsx
  services/ui-src/src/components/cards/EntityCard/EntityCardTopSection.tsx
  services/ui-src/src/components/export/ExportedEntityDetailsOverlaySection.tsx
  services/ui-src/src/components/export/ExportedEntityDetailsTable.test.tsx
  services/ui-src/src/components/export/ExportedEntityDetailsTable.tsx
  services/ui-src/src/components/export/ExportedEntityDetailsTableRow.tsx
  services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
  services/ui-src/src/components/export/ExportedPlanComplianceCard.test.tsx
  services/ui-src/src/components/export/ExportedPlanComplianceCard.tsx
  services/ui-src/src/components/export/ExportedPlanOverlayReportSection.test.tsx
  services/ui-src/src/components/export/ExportedPlanOverlayReportSection.tsx
  services/ui-src/src/components/export/ExportedReportBanner.tsx
  services/ui-src/src/components/export/ExportedSectionHeading.tsx
  services/ui-src/src/components/index.ts
  services/ui-src/src/components/layout/InfoSection.tsx
  services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
  services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
  services/ui-src/src/components/pages/GetStarted/ReportGetStartedPage.tsx
  services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.tsx
  services/ui-src/src/components/tables/SortableNaaarStandardsTable.tsx
  services/ui-src/src/utils/index.ts
  services/ui-src/src/utils/other/export.test.tsx
  services/ui-src/src/utils/other/export.tsx
  services/ui-src/src/utils/reports/entities.test.ts
  services/ui-src/src/utils/reports/entities.ts
  services/ui-src/src/utils/tables/mapNaaarStandardsData.test.ts
  services/ui-src/src/utils/tables/mapNaaarStandardsData.ts
  services/ui-src/src/utils/testing/mockForm.tsx
  services/ui-src/src/utils/verbiage/verbiage.test.ts
  services/ui-src/src/utils/verbiage/verbiage.ts
  services/ui-src/src/verbiage/pages/mcpar/mcpar-export.ts
  services/ui-src/src/verbiage/pages/mlr/mlr-export.ts
  services/ui-src/src/verbiage/pages/naaar/naaar-export.ts
Labels: feature, ready for review

#12160 Make header unsticky at small screen size/high zoom
  services/ui-src/src/components/layout/Header.tsx
Labels: ready for review

#12171 July 2025 MCPAR: Update State Fair Hearing hint text for one question
  services/app-api/forms/mcpar.json
Labels: ready for review

#12164 [CMDCT-4426] MCPAR Updates - Remove Ratio Questions
  services/app-api/forms/mcpar.json
Labels: ready for review, product review

#12167 [CMDCT-4574] MCPAR Updates - Access Measure Text Updates
  services/app-api/forms/mcpar.json
Labels: ready for review, product review

#12180 text updates for mcpar d1.iv.7b
  services/app-api/forms/mcpar.json
Labels: ready for review

#12181 add new mcpar appeals by service questions
  services/app-api/forms/mcpar.json
Labels: ready for review

#12173 Styling updates for NAAAR plan compliance and MLR reporting pages
  services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
  services/ui-src/src/components/reports/OverlayReportPage.tsx
  services/ui-src/src/components/tables/EntityRow.tsx
  services/ui-src/src/components/tables/ResponsiveEntityRow.tsx
Labels: ready for review

#12191 Flaky AddEditReportModal Test Fixes
  services/ui-src/src/components/modals/AddEditReportModal.test.tsx
Labels: ready for review

#12199 [CMDCT-4586] MCPAR Update - Topic VIII Sanctions Instruction
  services/app-api/forms/mcpar.json
Labels: ready for review

#12198 [CMDCT-4585] MCPAR Update - Text Updates for D1.IV.15b, D1.IV.16i, D1.IV.16c
  services/app-api/forms/mcpar.json
Labels: ready for review

#12197 [CMDCT-4584] MCPAR Update - New Grievances By Service Questions
  services/app-api/forms/mcpar.json
  tests/seeds/fixtures/mcpar.ts
Labels: ready for review

#12213 Add cognito error messaging
  services/ui-src/src/components/logins/LoginCognito.test.tsx
  services/ui-src/src/components/logins/LoginCognito.tsx
  services/ui-src/src/verbiage/errors.ts
Labels: do not merge, ready for review
